const actions = {
    SET_USER_ID: 'SET_USER_ID',

    GET_USER_ID_PENDING: 'GET_USER_ID_PENDING',
    GET_USER_ID_FULLFILLED: 'GET_USER_ID_FULLFILLED',
    GET_USER_ID_REJECT: 'GET_USER_ID_REJECT',

    SET_NAME: 'SET_NAME',
    SET_QOPTION: 'SET_QOPTION',
    SET_QOPTIONS: 'SET_QOPTIONS',
    SET_ADD_STATUS: 'SET_ADD_STATUS',
    SET_QUIZ_LIST: 'SET_QUIZ_LIST',
    SET_QUIZ_SELECTION: 'SET_QUIZ_SELECTION',
    SET_CORRECT_ANSWER: 'SET_CORRECT_ANSWER',
    SET_POINT: 'SET_POINT',
    SET_ORDER: 'SET_ORDER',
    SET_STATUS: 'SET_STATUS',
    SET_QUESTION_COUNT: 'SET_QUESTION_COUNT',
    SET_DESCRIPTION: 'SET_DESCRIPTION',
    SET_TITLE: 'SET_TITLE',
    SET_QUESTION_COUNT: 'SET_QUESTION_COUNT'
}

export {
    actions
}