const actions = {
    SET_BUILD_LIST: 'SET_BUILD_LIST',
    SET_BUILD_LIST_QUIZ: 'SET_BUILD_LIST_QUIZ',
    SET_BUILD_LIST_QUESTION: 'SET_BUILD_LIST_QUESTION',
    
    GET_BUILD_LIST: 'GET_BUILD_LIST',

    SET_USER_ID: 'SET_USER_ID',
    SET_USER_ID_REJECT: 'GET_USER_ID_REJECT',

    SET_ALL_QUIZ: 'SET_ALL_QUIZ',
    SET_ALL_QUESTION: 'SET_ALL_QUESTION',

    SET_NAME: 'SET_NAME',
    SET_QOPTION: 'SET_QOPTION',
    SET_QOPTIONS: 'SET_QOPTIONS',
    SET_ADD_STATUS: 'SET_ADD_STATUS',
    SET_QUIZ_LIST: 'SET_QUIZ_LIST',
    SET_QUIZ_SELECTION: 'SET_QUIZ_SELECTION',
    SET_CORRECT_ANSWER: 'SET_CORRECT_ANSWER',
    SET_POINT: 'SET_POINT',
    SET_ORDER: 'SET_ORDER',
    SET_STATUS: 'SET_STATUS',
    SET_QUESTION_COUNT: 'SET_QUESTION_COUNT',
    SET_DESCRIPTION: 'SET_DESCRIPTION',
    SET_TITLE: 'SET_TITLE',
    SET_QUESTION_COUNT: 'SET_QUESTION_COUNT'
}

export {
    actions
}